In [2]:
import pandas as pd
import numpy as np
from pymongo import MongoClient

In [3]:
# 방법2 - HOST, PORT
client = MongoClient(host='localhost', port=27017)

In [4]:
print(client.list_database_names())

['REAL', 'admin', 'config', 'local']

In [5]:
# 방법2
db = client['REAL']

In [6]:
# 방법2
collection = db['user']

In [7]:
# # Retrieve all documents in the collection
# all_documents = collection.find()

# all_data = list(all_documents)

In [8]:
all_data = list(collection.find({}, {'_id': 0}))  # Exclude '_id' field from the query
df = pd.DataFrame(all_data)

In [9]:
df

,저작자,제목,발행년도,ISBN,분류기호번호,장르,구매가격,2주일 대여 가격,1달 대여 가격,3달 대여 가격
0,조정래 지음,한강,2020,9788965743996,813.0,문학,15000,1500.0,3000.0,7500.0
1,박경리 지음,김약국의 딸들,2003,9788930005296,813.0,문학,12900,1290.0,2580.0,6450.0
2,로이스 버뎃 지음;윤미연 옮김,한여름 밤의 꿈,2002,9788990139016,842.0,문학,5100,510.0,1020.0,2550.0
3,노명희 글·그림,한여름 밤의 꿈,2002,9788952720238,842.0,문학,16000,1600.0,3200.0,8000.0
4,셰익스피어 원작;한미호 글;파블로바 그림,한여름 밤의 꿈,2003,9788901042893,808.0,문학,7900,790.0,1580.0,3950.0
...,...,...,...,...,...,...,...,...,...,...
522696,글: 송아주;그림: 원유미,착한 친구 감별법,2019,9791187903154,813.0,문학,10700,1070.0,2140.0,5350.0
522697,최광현 지음,"아들은 아버지의 등을 보고 자란다:이 시대의 남편, 아들, 아버지를 위한 자기회복 심리학",2023,9791191104592,189.0,철학,13200,1320.0,2640.0,6600.0
522698,송지현 지음,동해 생활 : 송지현 에세이,2022,9788937472800,814.0,문학,12500,1250.0,2500.0,6250.0
522699,"이길보라,이현화,황지성 지음",우리는 코다입니다 :소리의 세계와 침묵의 세계 사이에서,2019,9791187064428,338.0,사회과학,7400,740.0,1480.0,3700.0
522700,지은이: 봉태규,우리 가족은 꽤나 진지합니다 :봉태규 에세이,2019,9791160507331,818.0,문학,2000,200.0,400.0,1000.0

In [10]:
# '제목' 컬럼이 서로 다른 200개의 책을 뽑아서 20000개의 행을 구함
unique_titles = df['제목'].unique()
random_titles = pd.Series(unique_titles).sample(n=200, random_state=42).tolist()
choosen_books_df = df[df['제목'].isin(random_titles)].sample(n=20000, replace=True, random_state=42)
choosen_books_df

,저작자,제목,발행년도,ISBN,분류기호번호,장르,구매가격,2주일 대여 가격,1달 대여 가격,3달 대여 가격
146747,송도수 글,(코믹 메이플스토리) 수학도둑 : 기본편 . 12,2023,9791169236713,410.0,자연과학,2400,240.0,480.0,1200.0
490422,엘렌 델포르주 지음,인 러브,2023,9791198038722,864.0,문학,11400,1140.0,2280.0,5700.0
358944,정재승 기획,(정재승의) 인간 탐구 보고서,2021,9788950983147,511.0,기술과학,14900,1490.0,2980.0,7450.0
149671,"본회퍼, 디트리히",성도의 공동생활,2022,9791192675015,230.0,종교,1300,130.0,260.0,650.0
104069,금현진 손정혜; 정상민 [공]글; 이우일 그림,용선생의 시끌벅적 한국사 =,2023,9791162732687,911.0,역사,17400,1740.0,3480.0,8700.0
...,...,...,...,...,...,...,...,...,...,...
415051,느림 글·그림,열두 달 한뼘 텃밭:어린 농부를 위한 이십사절기 텃밭 농사,2022,9791163142430,521.0,기술과학,5600,560.0,1120.0,2800.0
271809,"닉 워드 글, 그림;윤의선 옮김",농부 조지 아저씨와 눈보라/,2002,9788984970915,843.0,문학,2400,240.0,480.0,1200.0
32412,정재은 글;김현민 그림,(정재승의) 인간 탐구 보고서,2023,9788950973735,511.0,기술과학,10200,1020.0,2040.0,5100.0
263163,한은화 지음,"아파트 담장 넘어 도망친 도시생활자:도심 속 다른 집, 다른 삶 짓기:큰글자도서",2022,9788962624588,617.0,예술,18100,1810.0,3620.0,9050.0
58066,수냐 지음,보글보글 기하,2021,9791190282192,415.0,자연과학,19700,1970.0,3940.0,9850.0

In [11]:
choosen_books_df['나이대'] = [ np.random.randint(1,7)*10 for _ in range(20000) ]
choosen_books_df['성별'] = [ np.random.randint(0,2) for _ in range(20000) ] 
choosen_books_df['구독여부'] = [ np.random.randint(0,2) for _ in range(20000) ]
choosen_books_df['구매 및 대여기간'] = [np.random.choice(['2주일', '1달', '3달','구매']) for _ in range(20000)]
choosen_books_df['평점'] = [ np.random.randint(1,6) for _ in range(20000)]

In [12]:
choosen_books_df['성별'] = choosen_books_df['성별'].apply(lambda x: '남자' if x ==1 else '여자')

In [13]:
choosen_books_df['구독여부'] = choosen_books_df['구독여부'].apply(lambda x: 'Y' if x ==1 else 'N')

In [14]:
choosen_books_df = choosen_books_df.reset_index(drop=True)
choosen_books_df

,저작자,제목,발행년도,ISBN,분류기호번호,장르,구매가격,2주일 대여 가격,1달 대여 가격,3달 대여 가격,나이대,성별,구독여부,구매 및 대여기간,평점
0,송도수 글,(코믹 메이플스토리) 수학도둑 : 기본편 . 12,2023,9791169236713,410.0,자연과학,2400,240.0,480.0,1200.0,50,여자,N,구매,4
1,엘렌 델포르주 지음,인 러브,2023,9791198038722,864.0,문학,11400,1140.0,2280.0,5700.0,40,여자,N,구매,5
2,정재승 기획,(정재승의) 인간 탐구 보고서,2021,9788950983147,511.0,기술과학,14900,1490.0,2980.0,7450.0,30,남자,Y,1달,2
3,"본회퍼, 디트리히",성도의 공동생활,2022,9791192675015,230.0,종교,1300,130.0,260.0,650.0,30,여자,Y,구매,3
4,금현진 손정혜; 정상민 [공]글; 이우일 그림,용선생의 시끌벅적 한국사 =,2023,9791162732687,911.0,역사,17400,1740.0,3480.0,8700.0,20,여자,Y,구매,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,느림 글·그림,열두 달 한뼘 텃밭:어린 농부를 위한 이십사절기 텃밭 농사,2022,9791163142430,521.0,기술과학,5600,560.0,1120.0,2800.0,40,남자,N,구매,5
19996,"닉 워드 글, 그림;윤의선 옮김",농부 조지 아저씨와 눈보라/,2002,9788984970915,843.0,문학,2400,240.0,480.0,1200.0,40,여자,Y,2주일,1
19997,정재은 글;김현민 그림,(정재승의) 인간 탐구 보고서,2023,9788950973735,511.0,기술과학,10200,1020.0,2040.0,5100.0,50,남자,Y,구매,2
19998,한은화 지음,"아파트 담장 넘어 도망친 도시생활자:도심 속 다른 집, 다른 삶 짓기:큰글자도서",2022,9788962624588,617.0,예술,18100,1810.0,3620.0,9050.0,30,여자,N,1달,4
19999,수냐 지음,보글보글 기하,2021,9791190282192,415.0,자연과학,19700,1970.0,3940.0,9850.0,60,여자,N,3달,5

In [15]:
grouped = choosen_books_df.groupby('제목')

for group_key, rows in grouped:
    rating_mean = np.mean(rows['평점'])
    choosen_books_df.loc[choosen_books_df['제목'] == group_key, '평균평점'] = round(rating_mean, 2)

In [16]:
choosen_books_df

,저작자,제목,발행년도,ISBN,분류기호번호,장르,구매가격,2주일 대여 가격,1달 대여 가격,3달 대여 가격,나이대,성별,구독여부,구매 및 대여기간,평점,평균평점
0,송도수 글,(코믹 메이플스토리) 수학도둑 : 기본편 . 12,2023,9791169236713,410.0,자연과학,2400,240.0,480.0,1200.0,50,여자,N,구매,4,2.96
1,엘렌 델포르주 지음,인 러브,2023,9791198038722,864.0,문학,11400,1140.0,2280.0,5700.0,40,여자,N,구매,5,3.00
2,정재승 기획,(정재승의) 인간 탐구 보고서,2021,9788950983147,511.0,기술과학,14900,1490.0,2980.0,7450.0,30,남자,Y,1달,2,3.07
3,"본회퍼, 디트리히",성도의 공동생활,2022,9791192675015,230.0,종교,1300,130.0,260.0,650.0,30,여자,Y,구매,3,3.05
4,금현진 손정혜; 정상민 [공]글; 이우일 그림,용선생의 시끌벅적 한국사 =,2023,9791162732687,911.0,역사,17400,1740.0,3480.0,8700.0,20,여자,Y,구매,1,3.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,느림 글·그림,열두 달 한뼘 텃밭:어린 농부를 위한 이십사절기 텃밭 농사,2022,9791163142430,521.0,기술과학,5600,560.0,1120.0,2800.0,40,남자,N,구매,5,2.89
19996,"닉 워드 글, 그림;윤의선 옮김",농부 조지 아저씨와 눈보라/,2002,9788984970915,843.0,문학,2400,240.0,480.0,1200.0,40,여자,Y,2주일,1,3.18
19997,정재은 글;김현민 그림,(정재승의) 인간 탐구 보고서,2023,9788950973735,511.0,기술과학,10200,1020.0,2040.0,5100.0,50,남자,Y,구매,2,3.07
19998,한은화 지음,"아파트 담장 넘어 도망친 도시생활자:도심 속 다른 집, 다른 삶 짓기:큰글자도서",2022,9788962624588,617.0,예술,18100,1810.0,3620.0,9050.0,30,여자,N,1달,4,3.05
19999,수냐 지음,보글보글 기하,2021,9791190282192,415.0,자연과학,19700,1970.0,3940.0,9850.0,60,여자,N,3달,5,3.24

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 사용자가 입력한 컬럼들만 선택
user_age = 30
user_gender = '여자'
user_is_subscription = 'Y'

# 책들의 정보와 유사한 사용자들을 찾기 위해 나이대, 성별, 구독여부를 필터링하여 동일한 사용자들의 데이터를 추출
similar_users = choosen_books_df.loc[
    (choosen_books_df['나이대'] == user_age) &
    (choosen_books_df['성별'] == user_gender) &
    (choosen_books_df['구독여부'] == user_is_subscription)
]

# 콘텐츠 기반 필터링을 위해 도서 제목을 벡터화
vectorizer = CountVectorizer()
title_matrix = vectorizer.fit_transform(choosen_books_df['제목'])

# 코사인 유사도 계산
cosine_sim = cosine_similarity(title_matrix)

# 유사한 사용자들이 선호하는 책들 중에서 사용자가 평점을 매긴 책과 유사도가 가장 높은 책을 추천
recommended_books = []

for book in similar_users['제목']:
    book_idx = choosen_books_df[choosen_books_df['제목'] == book].index[0]
    sim_scores = list(enumerate(cosine_sim[book_idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]  # 자기 자신을 제외하고 상위 5개 유사도 책들을 선택
    book_indices = [i[0] for i in sim_scores]
    recommended_books.extend(choosen_books_df['제목'].iloc[book_indices])

# 중복된 책들을 제거하고 인기도가 높은 순서대로 정렬하여 최종 추천 책을 선택
recommended_books = list(set(recommended_books))
recommended_books = choosen_books_df[choosen_books_df['제목'].isin(recommended_books)].sort_values(by='평균평점', ascending=False)[['제목', '평점']].reset_index(drop=True)

In [18]:
unique_books_df = recommended_books.drop_duplicates(subset='제목', keep='first')
unique_books_df

                                   제목  평점
0                 엄마 없는 아이와 아이 없는 엄마와   1
50                             화첩기행 1   3
100                   연필은 내 친구:연필 이야기   3
156       (눈앞의 달콤한 유혹,) 만원짜리는 줍지 마라 /   4
157                          내 꿈은 개그맨   4
...                               ...  ..
18933             쉿! 종묘에서 제례를 모시고 있어요   1
18983                  호랑이 뱃속에서 고래 잡기   1
19042                  태양계의 비밀을 찾는 모험   4
19108  메멧: 계절이 지나간 자리 =  : 계절이 지나간 자리   1
19158  Beasts of a little land:[영어도서]   5

[184 rows x 2 columns]

In [19]:
# 상위 10개의 추천 도서만 선택
top_10_recommended_books = unique_books_df.head(10)['제목'].values

In [20]:
print("10개 추천 도서:")
for book in top_10_recommended_books:
    print(book)

10개 추천 도서:
엄마 없는 아이와 아이 없는 엄마와
화첩기행 1
연필은 내 친구:연필 이야기
(눈앞의 달콤한 유혹,) 만원짜리는 줍지 마라 /
내 꿈은 개그맨
경제는 정치다:이헌재의 경제특강
나무도령 =(The) story of tree boy : rewritten by Choi Jeong-won, writer of children's books:아동문학가 최정원 선생님이 다시 쓴 우리 신화
Kids 50 English
챗GPT 질문하는 인간, 답하는 AI : 큰글자책
(7인 7색) 수채화 캘리그라피 : 7인 7색 개성가득 140개의 작품들